name: weather_app_tdd
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #TODO: Handle Success and Failure
  dartz: ^0.10.1

  # TODO: Compare to States and Objects
  equatable: ^2.0.5

  #TODO: State Management
  flutter_bloc: ^8.1.3

  #TODO: Dependencies Injection
  get_it: ^7.6.4

  #TODO: Requst to server
  http: ^1.1.0

  rxdart: ^0.27.7

  #TODO: State Management
  bloc: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  #TODO: flutter Test
  #> TODO: Test abstraction
  mockito: ^5.0.15
  mocktail: ^1.0.3
  dio: ^5.3.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
